Repository bcgov/jag-file-submission, pull requests merged in 2021-11, with the labels that each got.

#2304 Update facade
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingFacade.wsdl
Labels: porkchop sandwiches, wsdl, java, It's Working!, (⌐■_■)ノ＼(■_■ ), GOTTA GO FAST, MORE THAN MEETS THE EYE 🤖, :pizza: :label:, :vulcan_salute: QUARK, :bicyclist: cash, :badger: BADGER, :smile_cat: Cat, :cat: :cat2: :joy_cat: :smile_cat: :smirk_cat:, jedi :star:, EXTREME DEVOPS, :car:, :racing_car:, :3rd_place_medal:

#2305 Validate request
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/FilingpackageApiDelegateImpl.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/FilingPackageServiceImpl.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetReportTest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/submission/models/ReportRequest.java
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingFacade.wsdl
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingStatusFacade.wsdl
Labels: :badger: BADGER

#2306 Re WSDL Refresh
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingFacade.wsdl
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingStatusFacade.wsdl
Labels: :bicyclist: cash, :badger: BADGER, :cat: :cat2: :joy_cat: :smile_cat: :smirk_cat:, :car:, :3rd_place_medal:

#2307 Stop package review page from loading links when error occurs
  src/frontend/efiling-frontend/src/components/page/home/Home.test.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/__tests__/PackageConfirmation.test.js
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
  src/frontend/efiling-frontend/src/domain/package/package-review/__snapshots__/PackageReview.stories.storyshot
  src/frontend/efiling-frontend/src/domain/package/package-review/__tests__/PackageReview.test.js
  src/frontend/efiling-frontend/src/domain/package/package-review/__tests__/__snapshots__/PackageReview.test.js.snap
  src/frontend/efiling-frontend/src/domain/payment/__tests__/Payment.test.js
  src/frontend/efiling-frontend/src/modules/helpers/generateFileSummaryData.js
  src/frontend/efiling-frontend/src/storyshots.test.js
Labels: ICEMAN

#2318 Update Demo
  src/backend/libs/efiling-demo-starter/src/main/java/ca/bc/gov/open/jag/efiling/demo/EfilingDocumentServiceDemoImpl.java
  src/backend/libs/efiling-demo-starter/src/test/java/ca/bc/gov/open/jag/efiling/demo/EfilingDocumentServiceDemoImplTest.java
Labels: :badger: BADGER

#2330 fixed rush side card redirect errors
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
Labels: bug, frontend, frontend-tests, Mustard :spoon:

#2320 Hide rush radio buttons and set rush display to Yes when POR document is in the package
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/__tests__/PackageConfirmation.test.js
  src/frontend/efiling-frontend/src/modules/helpers/generateFileSummaryData.js
  src/frontend/efiling-frontend/src/modules/test-data/documentTestData.js
Labels: ICEMAN

#2333 Add get rush document
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/FilingPackageServiceImpl.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/FilingPackageConfigTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetRushDocumentTest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/model/RushDocumentRequest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/submission/EfilingReviewService.java
  src/backend/libs/efiling-cso-client/src/main/java/ca/bc/gov/open/jag/efilingcsoclient/CsoReviewServiceImpl.java
  src/backend/libs/efiling-cso-client/src/test/java/ca/bc/gov/open/jag/efilingcsoclient/csoReviewServiceImpl/GetRushDocumentTest.java
  src/backend/libs/efiling-demo-starter/src/main/java/ca/bc/gov/open/jag/efiling/demo/EfilingReviewServiceDemoImpl.java
  src/backend/libs/efiling-demo-starter/src/test/java/ca/bc/gov/open/jag/efiling/demo/EfilingReviewServiceDemoImplTest.java
Labels: porkchop sandwiches, java, It's Working!, (⌐■_■)ノ＼(■_■ ), GOTTA GO FAST, MORE THAN MEETS THE EYE 🤖, :pizza: :label:, :vulcan_salute: QUARK, :bicyclist: cash, :watch: sync :watch:, label, Label name, :badger: BADGER, :smile_cat: Cat, :cat: :cat2: :joy_cat: :smile_cat: :smirk_cat:, :fork_and_knife: fork, EXTREME DEVOPS, :car:, :racing_car:, :3rd_place_medal:, UNDERWHELMING

#2334 Adding demo data
  src/backend/libs/efiling-demo-starter/src/main/java/ca/bc/gov/open/jag/efiling/demo/EfilingLookupServiceDemoImpl.java
  src/backend/libs/efiling-demo-starter/src/test/java/ca/bc/gov/open/jag/efiling/demo/EfilingLookupServiceDemoImplTest.java
  tests/src/test/java/ca/bc/gov/open/jag/efiling/stepDefinitions/GetCountriesSD.java
Labels: java, It's Working!, (⌐■_■)ノ＼(■_■ ), GOTTA GO FAST, MORE THAN MEETS THE EYE 🤖, over1000, :pizza: :label:, :vulcan_salute: QUARK, :bicyclist: cash, :badger: BADGER, :smile_cat: Cat, :cat: :cat2: :joy_cat: :smile_cat: :smirk_cat:, :fork_and_knife: fork, EXTREME DEVOPS, :car:, :racing_car:, :3rd_place_medal:, UNDERWHELMING

#2331 Fixed area code handling on rush processing screen
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/components/page/rush/Rush.test.js
  src/frontend/efiling-frontend/src/modules/helpers/StringUtil.js
Labels: ICEMAN

#2336 fixed remove file error
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/components/page/rush/rush-document-list/RushDocumentList.js
  src/frontend/efiling-frontend/src/components/page/rush/rush-document-list/RushDocumentList.test.js
  src/frontend/efiling-frontend/src/components/page/rush/rush-document-list/RushDocumentListItem.js
Labels: frontend, frontend-tests, Mustard :spoon:, some cute bees for your PR :bee: :bee: :bee:

#2338 Fixed incorrect check for null rush on a package
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
  src/frontend/efiling-frontend/src/domain/package/package-review/__tests__/PackageReview.test.js
  src/frontend/efiling-frontend/src/domain/package/package-review/__tests__/__snapshots__/PackageReview.test.js.snap
Labels: bug, handle it, mostly snapshot tests :camera:

#2340 Changed null check on package review page to fix POR error
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
Labels: ICEMAN

#2339 Added package files to duplicate file check on rush
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/components/page/rush/Rush.test.js
Labels: ICEMAN

#2351 Moved protection order check outside of rush check
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
Labels: ICEMAN
