Repository bcgov/jag-file-submission, pull requests merged in 2021-12, with the labels that each got.

#2335 Removed alphabetic character requirement on first and last name fields
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/components/page/rush/Rush.test.js
Labels: ICEMAN, More Labels!

#2355 Fix date parsing
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/mappers/RushProcessingMapper.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/submissionApiDelegateImpl/PostRushProcessingTest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/utils/DateUtils.java
Labels: :pizza: :label:, :bicyclist: cash, :badger: BADGER, :smile_cat: Cat, :fork_and_knife: fork, :car:, :3rd_place_medal:

#2359 Fixed supporting documents on submit rush call
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/mappers/RushProcessingMapper.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/CreateSubmissionTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/submissionApiDelegateImpl/SubmitTest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/model/RushProcessing.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/utils/DateUtils.java
  src/backend/libs/efiling-cso-client/src/main/java/ca/bc/gov/open/jag/efilingcsoclient/CsoSubmissionServiceImpl.java
  src/backend/libs/efiling-cso-client/src/test/java/ca/bc/gov/open/jag/efilingcsoclient/csoSubmissionServiceImpl/SubmitFilingPackageTest.java
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  tests/src/test/resources/features/rushProcessing.feature
Labels: java, javascript, TEAMWORK! (⌐■_■), ICEMAN

#2371 Add Rush Required and Update Status
  src/backend/efiling-api/jag-efiling-api.yaml
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/FilingPackageConfig.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/mapper/FilingPackageMapper.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/FilingPackageServiceImpl.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/SubmissionApiDelegateImpl.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/SubmissionConfig.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/service/SubmissionService.java
  src/backend/efiling-api/src/main/java/ca/bc/gov/open/jag/efilingapi/submission/service/SubmissionServiceImpl.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/FilingPackageConfigTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/DeleteSubmittedDocumentTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetActionRequiredDetailsTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetCSOFilingPackageTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetFilingPackagesTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetParentAppDetailsTestTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetReportTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetRushDocumentTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/filingpackage/service/filingPackageServiceImpl/GetSubmissionDocumentTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/CreateSubmissionTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/GenerateFromRequestTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/GetValidIndividualRolesTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/IsRushRequiredTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/service/submissionServiceImpl/UpdateDocumentsTest.java
  src/backend/efiling-api/src/test/java/ca/bc/gov/open/jag/efilingapi/submission/submissionApiDelegateImpl/GetPackageInformationTest.java
  src/backend/libs/efiling-commons/src/main/java/ca/bc/gov/open/jag/efilingcommons/submission/models/review/ReviewDocument.java
  src/backend/libs/efiling-cso-client/src/main/java/ca/bc/gov/open/jag/efilingcsoclient/CsoSubmissionServiceImpl.java
Labels: :pizza: :label:, :bicyclist: cash, :badger: BADGER, :smile_cat: Cat, :car:, :racing_car:, :3rd_place_medal:

#2372 added rushRequired attribute to tests
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
  src/frontend/efiling-frontend/src/modules/test-data/documentTestData.js
  src/frontend/efiling-frontend/src/modules/test-data/packageReviewTestData.js
Labels: frontend, frontend-tests, :bicyclist: cash, :badger: BADGER, Mustard :spoon:, EXTREME DEVOPS

#2373 Fix null pointer in name
  src/frontend/efiling-frontend/src/domain/package/package-review/PackageReview.js
Labels: (⌐■_■)ノ＼(■_■ ), :pizza: :label:, :vulcan_salute: QUARK, :bicyclist: cash, :badger: BADGER, :fork_and_knife: fork, EXTREME DEVOPS, :car:, :racing_car:, :3rd_place_medal:

#2375 updated dependabot to target correct branch
  .github/dependabot.yml
Labels: EXTREME DEVOPS

#2374 Fix package confirmation rush status display
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/__tests__/PackageConfirmation.test.js
Labels: (⌐■_■)ノ＼(■_■ ), ICEMAN

#2379 Fixed sidecard link, fixed rush display on payment
  src/frontend/efiling-frontend/src/components/page/rush/Rush.js
  src/frontend/efiling-frontend/src/components/page/rush/Rush.test.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/PackageConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/RushConfirmation.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/__tests__/PackageConfirmation.test.js
  src/frontend/efiling-frontend/src/domain/package/package-confirmation/__tests__/__snapshots__/PackageConfirmation.test.js.snap
  src/frontend/efiling-frontend/src/domain/payment/Payment.js
  src/frontend/efiling-frontend/src/domain/payment/__snapshots__/Payment.stories.storyshot
  src/frontend/efiling-frontend/src/domain/payment/__tests__/Payment.test.js
  src/frontend/efiling-frontend/src/domain/payment/__tests__/__snapshots__/Payment.test.js.snap
  src/frontend/efiling-frontend/src/modules/helpers/sidecardData.js
Labels: frontend, Mustard :spoon:, mostly snapshot tests :camera:

#2385 Move to version 1.2.0
  src/backend/efiling-api/pom.xml
  src/backend/libs/efiling-bambora-api-client/pom.xml
  src/backend/libs/efiling-bom/pom.xml
  src/backend/libs/efiling-ceis-api-client/pom.xml
  src/backend/libs/efiling-commons/pom.xml
  src/backend/libs/efiling-cso-client/pom.xml
  src/backend/libs/efiling-cso-starter/pom.xml
  src/backend/libs/efiling-demo-starter/pom.xml
  src/backend/libs/efiling-mail-it/pom.xml
  src/backend/pom.xml
Labels: version, :bicyclist: cash, :car:, :3rd_place_medal:

#2386 Fix log4j version
  src/backend/efiling-api/pom.xml
  src/backend/libs/efiling-bambora-api-client/pom.xml
  src/backend/libs/efiling-bom/pom.xml
  src/backend/libs/efiling-ceis-api-client/pom.xml
  src/backend/libs/efiling-commons/pom.xml
  src/backend/libs/efiling-cso-client/pom.xml
  src/backend/libs/efiling-cso-starter/pom.xml
  src/backend/libs/efiling-demo-starter/pom.xml
  src/backend/libs/efiling-mail-it/pom.xml
  src/backend/pom.xml
  tests/pom.xml
Labels: :3rd_place_medal:

#2389 Add prod wsdls
  src/backend/efiling-api/pom.xml
  src/backend/libs/efiling-bambora-api-client/pom.xml
  src/backend/libs/efiling-bom/pom.xml
  src/backend/libs/efiling-ceis-api-client/pom.xml
  src/backend/libs/efiling-commons/pom.xml
  src/backend/libs/efiling-cso-client/pom.xml
  src/backend/libs/efiling-cso-client/src/main/java/ca/bc/gov/open/jag/efilingcsoclient/CsoSubmissionServiceImpl.java
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingFacade.wsdl
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingStatusFacade.wsdl
  src/backend/libs/efiling-cso-starter/pom.xml
  src/backend/libs/efiling-demo-starter/pom.xml
  src/backend/pom.xml
Labels: :badger: BADGER, :3rd_place_medal:

#2392 Revert WSDL's
  src/backend/libs/efiling-cso-client/src/main/java/ca/bc/gov/open/jag/efilingcsoclient/CsoSubmissionServiceImpl.java
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingFacade.wsdl
  src/backend/libs/efiling-cso-client/src/main/resources/wsdl/FilingStatusFacade.wsdl
Labels: java, It's Working!, (⌐■_■)ノ＼(■_■ ), :bicyclist: cash, :badger: BADGER, :cat: :cat2: :joy_cat: :smile_cat: :smirk_cat:, EXTREME DEVOPS, :car:

#2393 Update to new snapshot version
  src/backend/efiling-api/pom.xml
  src/backend/libs/efiling-bambora-api-client/pom.xml
  src/backend/libs/efiling-bom/pom.xml
  src/backend/libs/efiling-ceis-api-client/pom.xml
  src/backend/libs/efiling-commons/pom.xml
  src/backend/libs/efiling-cso-client/pom.xml
  src/backend/libs/efiling-cso-starter/pom.xml
  src/backend/libs/efiling-demo-starter/pom.xml
  src/backend/libs/efiling-mail-it/pom.xml
  src/backend/pom.xml
Labels: (⌐■_■)ノ＼(■_■ ), version, :vulcan_salute: QUARK, :bicyclist: cash, :badger: BADGER, :car:, :3rd_place_medal:

#2399 Update splunk to 1.11.2
  src/backend/efiling-api/pom.xml
  src/backend/libs/efiling-bambora-api-client/pom.xml
  src/backend/libs/efiling-bom/pom.xml
  src/backend/libs/efiling-ceis-api-client/pom.xml
  src/backend/libs/efiling-commons/pom.xml
  src/backend/libs/efiling-cso-client/pom.xml
  src/backend/libs/efiling-cso-starter/pom.xml
  src/backend/libs/efiling-demo-starter/pom.xml
  src/backend/pom.xml
Labels: :bicyclist: cash, :badger: BADGER, :3rd_place_medal:
